#.Travis.yml
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r learn-spring-boot *
  - mkdir -p deploy
  - mv learn-spring-boot.zip deploy/learn-spring-boot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: learn-spring-boot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

before_install:
  - chmod +x gradlew

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - xjfcnfw3@naver.com