#.Travis.yml
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/learn_spring_boot.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-spring-boot
    region: ap-northeast-2
    acl: private
    skip_cleanup: true
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-spring-boot
    key: learn_spring_boot.zip
    bundle_type: zip
    application: test-spring-boot
    deployment_group: test-spring-boot-group
    region: ap-northeast-2
    wait-until-deployed: true


before_install:
  - chmod +x gradlew

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - xjfcnfw3@naver.com